### ISSUE TITLE
UI stays open after closing.

### ISSUE THREAD

**Issue by penloy** [terrarier2111/Leafish#106] opened 2021-09-06 04:20 UTC
Distro: Pop!_OS 20.04

Steps to reproduce bug:

1. Connect to a server
2. Press escape to open menu
3. Open any of the options (i.e. Audio settings... Video settings...)
4. Press escape to exit

The result is that you will be in the pause menu and able to move around as well in game, unable to click any of the options. The only solution is to disconnect and reconnect to the server.

**Comment by schitcrafter** [comment] 2021-09-06 09:53
Duplicate #97

**Comment by PureTryOut** [comment] 2021-09-06 13:10
Closing as duplicate of #97

**Closed by PureTryOut** 2021-09-06 13:10 UTC
